### ISSUE TITLE
Trying to import Global CSS in when referencing KeyMod

### ISSUE THREAD

**Issue by subwaymatch** [suren-atoyan/monaco-react#101]
**Describe the bug**

First off, this package is amazing since I don't need to pollute the Webpack configuration with dirty workarounds. Thanks for creating this package :pray:.

I am using `ControlledEditor` with Next.js + Typescript. Once the editor is mounted, I want to add a Keyboard command using `editor.addCommand()`. However, Next.js throws an `Global CSS cannot be imported from within node_modules.` error as soon as I reference `KeyMod.CtrlCmd` in `monaco-editor/esm/vs/editor/editor.api`.

**imports:** 
![image](https://user-images.githubusercontent.com/1064036/89743850-e023ff00-da6c-11ea-89ac-8714ff88ab8b.png)

**What happens without a reference to `KeyMod`.**
Builds successfully
![image](https://user-images.githubusercontent.com/1064036/89741613-3cc8ef00-da58-11ea-8a11-6feee019c61c.png)
![image](https://user-images.githubusercontent.com/1064036/89741609-363a7780-da58-11ea-8233-e15ccba8bf8f.png)

**What happens with a reference to KeyMod**
[Error](https://github.com/vercel/next.js/blob/master/errors/css-npm.md) while building
![image](https://user-images.githubusercontent.com/1064036/89741519-9aa90700-da57-11ea-8fb1-31fb53a24247.png)
![image](https://user-images.githubusercontent.com/1064036/89741530-ad234080-da57-11ea-84d6-1e9a1970a93c.png)

**To Reproduce**
The problem is reproduced in [this CodeSandbox](https://codesandbox.io/s/monaco-react-global-css-error-xus24?file=/pages/index.tsx). 

`monaco-react` renders fine without the `editor.addCommand(KeyMod.CtrlCmd, ...)` line. 

1. Go to [this CodeSandbox](https://codesandbox.io/s/monaco-react-global-css-error-xus24?file=/pages/index.tsx)
2. Uncomment the line with `KeyMod.CtrlCmd`.

**Expected behavior**
No reference to Global CSS

**Screenshots**
I've added the screenshots above.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Both in Windows 10 and MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  84.0.4147.105

**Additional context**

**Comment by subwaymatch** [comment]
For now, I'm manually using the enum numbers 3 and 2048 to work around this issue.

```javascript
const handleEditorDidMount: EditorDidMount = (_, editor) => {
    // 3 == KeyCode.Enter, 2048 == KeyMod.CtrlCmd
    editor.addCommand(3 | 2048, () => {
      alert('CmdCtrl + Enter Pressed!');
    });
};
```

**Comment by suren-atoyan** [comment]
Hello @subwaymatch.

Thank you for your feedback!

The problem is that `monaco-editor/esm/vs/editor/editor.api` tries to load some CSS, which is unacceptable for `next.js` (as it is global and comes from `node_modules`). `monaco-editor` package is out of my control, I can't fix it, so, you can open issue in their repo if you want. But, the good news is, that you don't need it. The library gives you an opportunity to access `KeyMod`; for that, you can use [monaco instance](https://github.com/suren-atoyan/monaco-react#monaco-instance). [Here](https://codesandbox.io/s/monaco-editorreact---monaco-instance-5pbmx?fontsize=14&hidenavigation=1&theme=dark) is an example. I fixed your example as well, check it [here](https://codesandbox.io/s/monaco-react-issue-101-u1g1w?file=/pages/index.tsx).

Let me know if it helps.

**Comment by subwaymatch** [comment]
@suren-atoyan I don't know if there is a way to thank you enough :clap:. 

![image](https://user-images.githubusercontent.com/1064036/89793769-ddb4ba00-daeb-11ea-826a-74433a0a0b46.png)

On a serious note though, this package should be the (un)official React binding for `monaco-editor`. Thank you once again and I'm closing the issue.
