### ISSUE TITLE
Editor Syncing Issue

### ISSUE THREAD

**Issue by davies-jack** [suren-atoyan/monaco-react#102]
**Describe the bug**
When two editors are on the page, and the value is being conditionally chosen: if both editors at any point have the same content in both, they will sync up meaning both editors will have the same content, and if you type into one, the content shows in the other.

**To Reproduce**

1. Go to [the code example (codesandbox)](https://codesandbox.io/s/react-monaco-sync-bug-umjs1)
2. Type something in the editor on Tab 0.
3. Copy and paste this into Tab 1.
4. Go back to Tab 0.
5. Type something new in Tab 0.
6. Go to Tab 1. It will be the same content.

**Expected behavior**
Both editors to have separate values, and not to sync.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome, tested on Firefox too
 - Version 84 (chrome) 79 (firefox)

**Comment by jackethdavies** [comment]
As an update to this, a fix is to pass each editor a unique `key`

`<Editor
value={code}
key={uniqueKey}
/>`

**Comment by suren-atoyan** [comment]
Hello @davies-jack, sorry for the late answer

The problem is that, here, we work with the same model. When the `Editor` component mounts, it creates a single model. By changing language, value, or options technically you interact with the same model. When you pass a new key, you force to mount/unmount the `Editor` component, which creates a new model. So, to work with multiple files/tabs you can manually handle model creation; read [this](https://github.com/suren-atoyan/monaco-react/issues/148) discussion. In the next major version, I'll add an API for easily working with multiple models.
