### ISSUE TITLE
Render Popover by using React.createPortal with editor.addContentWidget

### ISSUE THREAD

**Issue by theprimone** [suren-atoyan/monaco-react#124]
**Describe the bug**
Popover can't close if opened

**To Reproduce**

[codesandbox](https://codesandbox.io/s/monaco-editor-demo-7742z?file=/src/App.js:1918-1934)

**Expected behavior**
Popover closed when mouse leave like: [codesandbox](https://codesandbox.io/s/render-popover-with-reactdomcreateportal-n9kue?file=/index.js)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 86.0.4240.111

**Comment by suren-atoyan** [comment]
Hello @theprimone, sorry for the late answer.

I reckon it's not related to the editor, because, first of all, I don't see the trigger to close the popover.

[Here](https://codesandbox.io/s/monaco-editor-demo-forked-m1vqs?file=/src/App.js) your same code, without the `Editor` component. I removed the `Editor` component and render just a div with the expected id. The "problem" of the popover is the same.
