### ISSUE TITLE
DiffEditor is invisible until resizing the viewport

### ISSUE THREAD

**Issue by andreasremdt** [suren-atoyan/monaco-react#128]
**Describe the bug**
When adding the DiffEditor to a page, it is initially invisible. The wrapper and all DOM nodes are mounted, but the screen is empty (only a small part is visible on the top left corner). If you resize the viewport, it appears all of the sudden.

**To Reproduce**
1. Go to https://codesandbox.io/s/condescending-pond-f1mo0?fontsize=14&hidenavigation=1&theme=dark
2. Look at the browser preview. It should not show the editor.
3. Resize your browser or the preview window in CodeSandbox.

**Expected behavior**
I would expect the editor to be visible right after mounting.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome, Firefox
 - Version: latest

**Comment by suren-atoyan** [comment]
Hello @andreasremdt 

There is an issue in monaco version 0.20.0. The current version of the library uses that very version, [check it out](https://github.com/suren-atoyan/monaco-react/blob/master/src/config/index.js). It's already fixed in version 0.21. You can configure the library to use the latest version. I've created an example for that, [here](https://codesandbox.io/s/compassionate-euclid-2ci09?file=/src/App.js) it is.

**Comment by andreasremdt** [comment]
Hey! Awesome, thank you for the quick and helpful response. Do you plan to upgrade internally to 0.21 in the future?

**Comment by suren-atoyan** [comment]
Yes, sure. In the next version (probably next week) it will be updated.

**Comment by suren-atoyan** [comment]
Hello @andreasremdt, I just wanted to inform you, that the new version is released today (v3.7.0) where monaco version is updated to 0.21.2

**Comment by andreasremdt** [comment]
Cool, thank you for the update and for letting me know :+1:
