### ISSUE TITLE
Please remove the LGPL copyrights from your production install

### ISSUE THREAD

**Issue by scottdickerson** [suren-atoyan/monaco-react#156]
**Describe the bug**
There is reference to LGPL licenses in your demo/example files. Unfortunately these are installed as part of your production installation.  Can you please remove the licensed code or remove these files from your production install?

Here's the file with the LGPL content
https://github.com/suren-atoyan/monaco-react/blob/master/demo/src/config/examples.js

**To Reproduce**

Install for production, scan your node_modules files

**Comment by suren-atoyan** [comment]
Hello @scottdickerson 

Could you please tell me which version of the library you use? Because the `demo` folder under `.npmignore`, so, it can't be included in the production build. [Here](https://github.com/suren-atoyan/monaco-react/blob/master/.npmignore#L9) is the `.npmignore` file

Also, here is a screenshot of the `node_modules` one of the projects which uses the latest version of the library

<img width="240" alt="Screen Shot 2021-01-04 at 20 49 04" src="https://user-images.githubusercontent.com/13118722/103558975-dfce4980-4ece-11eb-8b02-2a98c3f1ad32.png">

As you can see there is no `demo` folder

**Comment by scottdickerson** [comment]
you're right, I think this is an issue with our scan tool, thanks for helping out.
