### ISSUE TITLE
How to bypass jsdelivr

### ISSUE THREAD

**Issue by nsisodiya** [suren-atoyan/monaco-react#168]
We are installing our app in close env where Internet access will not be possible. that means, everything need to be bundled in the Docker image.
Currently the package make call to external js file.
`https://cdn.jsdelivr.net/npm/monaco-editor@0.21.2/min/vs/loader.js`

Please help to suggest the best way to resolve this issue. we want all these files in the bundle itself.

**Comment by suren-atoyan** [comment]
Hello @nsisodiya 

The package is configurable, so, you can download the sources, for example from your local files. You can do the following:

1) install `monaco-editor` package

```bash
npm install monaco-editor # or yarn add monaco-editor
```

2) configure the `loader`

```javascript
import { loader } from '@monaco-editor/react';

loader.config({ paths: { vs: 'path-to-your-node_modules/node_modules/monaco-editor/min/vs' } });
```

That's all.

Note that, based on your web server `node_modules` can be accessible or not. For example, if you use `create-react-app` the `public` folder is always accessible, after the first step (`monaco-editor` installation) you can copy `monaco-editor` folder from `node_modules` to `public`. Something like this:

```bash
cp -R node_modules/monaco-editor public/
```

And configure the loader like this:

```javascript
import { loader } from '@monaco-editor/react';

loader.config({ paths: { vs: '/monaco-editor/min/vs' } });
```

let me know if it helps

**Comment by nsisodiya** [comment]
@suren-atoyan 
I got the solution but can we improve it?
1. current solution involve paste node_modules folder in the git code.

is it possible to have `import` statement like we add other libs?

**Comment by suren-atoyan** [comment]
Hello @nsisodiya 

Putting `node_modules` in the git code can't be a solution. Please, don't do that.

You do `import` it like other libs, but if you want to change the source paths you need to configure it.
Rather than putting `node_modules` in the git code, you can extract `monaco-editor` from the `node_modules`.

**Comment by bobbui** [comment]
Hi @suren-atoyan 
I tried to do it but seem the loader config is still pointing to the default value
```
import {loader} from "@monaco-editor/react";
loader.config = {paths: {vs: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.22.1/min/vs',},}
```

Any idea?

**Comment by suren-atoyan** [comment]
Hey @bobbui, `loader.config` a function, you should call it, not reassign it. [Check this out](https://github.com/suren-atoyan/monaco-react#loader-config)

**Comment by bobbui** [comment]
> Hey @bobbui, `loader.config` a function, you should call it, not reassign it. [Check this out](https://github.com/suren-atoyan/monaco-react#loader-config)

@suren-atoyan yay! its working now. I cant believe my own stupidity.

**Comment by rajiff** [comment]
Hi

In my React App (created using create-react-app), I kept on getting issue about content policy as below

`Refused to load the script 'https://cdn.jsdelivr.net/npm/monaco-editor@0.21.2/min/vs/loader.js' because it violates the following Content Security Policy`

So i tried bypass the CDN, i followed the above, but yet getting this error, any idea what i am missing

![image](https://user-images.githubusercontent.com/1080415/112425298-d7620e00-8d5b-11eb-8a21-21225ba326ee.png)

**Comment by suren-atoyan** [comment]
@collabsoft 

> were not able to get them working.

what was the issue?

**Comment by collabsoft** [comment]
@suren-atoyan , thanks for the response.

The issue is the same loader problem calling outside of the environment.  I tried everything to configure it as you previously suggested,  including copying the module files to the src dir.  But for some reason the loader still insists on trying to call out and ultimately errors out since the environment is locked down.

**Comment by sklinov** [comment]
@suren-atoyan I'm running into `Cannot read properties of undefined (reading 'config')` issue when trying to call `loader.config({...})`
Is there a way to fix this?

Maybe import something from `monaco-editor` and then pass it to `@monaco-editor/react`?
Was there a particularly strong reason to fetch it from CDN and not include normally as a dependency so it gets bundled?

**Comment by sklinov** [comment]
Seems that this solution works
```
import * as monaco from 'monaco-editor';
import { loader } from '@monaco-editor/react';

loader.config({ monaco });
```
but only in combination with `monaco-editor`@`0.30.0`
