### ISSUE TITLE
Editor with a custom language breaks when rendering another editor with a different language

### ISSUE THREAD

**Issue by kushniro** [suren-atoyan/monaco-react#180]
I am attempting to use an editor with a custom language and theme and open a modal with an editor in another language. When I create the second editor (in a modal or not) the initial modal with the custom language and theme seems to break.

I've created a small reproduction using the custom language from the monaco playground and sql:
https://codesandbox.io/s/morning-silence-rx6is

any idea as to what's going on and how I can fix it?

thanks.

**Comment by suren-atoyan** [comment]
Hello @kushniro 

I guess the problem is in the custom theme rather than in the custom language, and it's related to the original package, not the wrapper. I've just tested in the [monaco playground](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages):

- create another editor in the playground

<img width="547" alt="Screen Shot 2021-02-14 at 22 25 46" src="https://user-images.githubusercontent.com/13118722/107885418-af3cef00-6f13-11eb-9b5f-d249882731d8.png">

- don't forget to create the second container for the second editor

<img width="487" alt="Screen Shot 2021-02-14 at 22 27 37" src="https://user-images.githubusercontent.com/13118722/107885464-e90df580-6f13-11eb-8a8b-798315839120.png">

And run it. Syntax highlighting is broken (everything else works, so far I noticed). When we remove `58` line (`theme: 'myCoolTheme',`) it works. So, something is wrong with the custom team definition, I think it should be referred to the original repo.

**Comment by kushniro** [comment]
thanks for replying @suren-atoyan ! 
I will try addressing the issue to monaco

**Comment by suren-atoyan** [comment]
@kushniro just in case, there is [multi-model editor](https://github.com/suren-atoyan/monaco-react#multi-model-editor) support, if you have more than one editors, you might be interested in that.

**Comment by kushniro** [comment]
for future reference, monaco supports a single theme for all editors on page [338](https://github.com/microsoft/monaco-editor/issues/338)
