### ISSUE TITLE
Support for `editor.setPosition` using a `position` prop

### ISSUE THREAD

**Issue by morpheus-14** [suren-atoyan/monaco-react#257]
I just implemented a definitionProvider on a multi model editor, where i needed to set position of new model using the react wrapper.

Although you provide the editor instance and the application can call it directly, it would be nice to have a `position` prop as well, where we use [`editor.setPosition`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandalonecodeeditor.html#setposition).

The wrapper component does provide a property for `line` where you are using [`editor.revealLine`](https://github.com/suren-atoyan/monaco-react/blob/master/src/Editor/Editor.js#L108). Maybe we could have a generic `position` prop as well.

**Comment by suren-atoyan** [comment]
the existence of the `line` property has some historical causes. If I design it now, I won't include the `line` property as well as other such kinds of properties (`position` too). The problem is that there are too many options, and projecting them into the component API isn't an optimal approach; from an overhead perspective as well as from a semantic perspective. The only options we've provided are value, language, and path. The other options can be implemented manually on demand.

BTW; if you use a [multi-model editor](https://github.com/suren-atoyan/monaco-react#multi-model-editor) you can use [saveViewState](https://github.com/suren-atoyan/monaco-react#props) property to keep the model's view-state (text selection, undo stack, scroll position, etc) during switching models
