### ISSUE TITLE
Missing wrapperClassName in 4.3.*

### ISSUE THREAD

**Issue by avalenti89** [suren-atoyan/monaco-react#294]
**Describe the bug**
I have 4.2.2 in my package but, if I remove my lock/node_modules and reinstall packages, I will get the newer version that has a Breaking Change on it.
In the new version of the library, you added "wrapperProps" property, but you removed the old props like "wrapperClassName".

You haven't added types to "wrapperProps". "object" type is not enough for a new prop.

**Expected behavior**
I expect that old props were handled as Deprecated (or that the new version were a major release).
I expect that wrapperProps has a good type definition. Eg:
`type WrapperProps = Omit<JSX.intrinsicElements['div'],'children'> & { ... };`

**Screenshots**
![image](https://user-images.githubusercontent.com/19409732/135981151-741e5cfd-8130-4ff8-a61e-4aa4bb5fbc76.png)

**Comment by suren-atoyan** [comment]
@avalenti89 you are right, I totally agree with you, it's my fault; the `wrapperClassName` should have been kept for backward compatibility and should have been made deprecated since there is no major version update. And type definition file should be re-written.

I'll include them in the new version.

**Comment by suren-atoyan** [comment]
Also, I'll appreciate any help in `types.d.ts` file update

**Comment by avalenti89** [comment]
@suren-atoyan I'll help you in my free time :) (I'm at work right now)
