### ISSUE TITLE
Type information 'leaking' between models

### ISSUE THREAD

**Issue by jjhuff** [suren-atoyan/monaco-react#308]
**Describe the bug**
When using multiple models, type info seems to 'leak' between models/editor instances

**To Reproduce**
Sandbox: https://codesandbox.io/s/multi-model-editor-forked-hig6i
1. Toggle between `script1.js` and `script2.js`
2. Start typing `bar` under `script1.js`
3. Notice that you get `bar` as a suggestion

**Expected behavior**
Models should be isolated

**Desktop (please complete the following information):**
 - Version: Appears in 4.3.1 but not 4.0.4

**Comment by suren-atoyan** [comment]
Hey @jjhuff 👋 

I've just checked the snippet, and yes, you are right, the issue exists. But I also tried to reproduce it in the [monaco-playground](https://microsoft.github.io/monaco-editor/playground.html) to be sure if the issue related to the react wrapper or to the original package. And it seems the issue is related to the original package. To reproduce it try the code below in the above-mentioned playground.


```js
const model1 = monaco.editor.createModel(`
const foo=1;
`, 'javascript', 'root/js/file1.js');

const model2 = monaco.editor.createModel(`
const foo=2;
const bar=3;
`, 'javascript', 'root/js/file2.js');

const editor = monaco.editor.create(document.getElementById('container'), {
    model: model1,
});

setTimeout(() => {
  editor.setModel(model2);
}, 500);

setTimeout(() => {
  editor.setModel(model1);
}, 1000);

```

**Comment by jjhuff** [comment]
Awesome, thanks for the playground snippet! I filed over on the main project.
