### ISSUE TITLE
addCommand is not getting updated state in functional component

### ISSUE THREAD

**Issue by saincogt** [suren-atoyan/monaco-react#328]
I would like to add a command which will reply on a local state value, something like this:

```js
const [count, setCount] = useState(0);
const onMount = (editor, monaco) => {
  if (editor) {
    editor.addCommand(monaco.KeyCode.Enter, () => console.log(count), '!suggestWidgetVisible');
  }
};

const onChange = () => setCount(count + 1);

return (
  <Editor
    height='30vh'
    onMount={onMount}
    onChange={onChange}
  />
);
```

When we start typing something the state value `count` is getting updated as expected, but when we press the Enter key, the console always prints `0`. Any idea why?

The weird thing is if I re-write the component in a class-based style, it will work.

Please let me know if I have missed anything.

Thank you.

**Comment by suren-atoyan** [comment]
actually, it's working as expected. `onMount` is being called just once, and it has no reference to the updated versions of `count`. there are many ways to overcome this - you can use `useRef` for example.

**Comment by yaralahruthik** [comment]
@suren-atoyan this is okay if you bind variables to the ref and use it, but what about functions? I have this issue where if a function depends on variables, and the variables change. Then only the first instance of that variables is used!
I added the command on every update to the function with useEffect but this turned out to be a huge performance issue!

**Comment by suren-atoyan** [comment]
@yaralahruthik you can use `useRef` for functions as well. Check [this](https://github.com/suren-atoyan/monaco-react/issues/277#issuecomment-900586372) please
