### ISSUE TITLE
No way to add keybindings with monaco-react? 

### ISSUE THREAD

**Issue by AndrewRayCode** [suren-atoyan/monaco-react#338]
**Describe the bug**
Calling `editor.addAction()` in `onMount` has no effect.

I've created  reproducible example in a codesandbox. You can see the keybinding is never triggered, no matter what keys are used: https://codesandbox.io/s/monaco-editor-react---playground-forked-i461e?file=/src/index.js

**Comment by suren-atoyan** [comment]
@AndrewRayCode it doesn't work because:

1) it's not `KeyCode.KeyE`, but `KeyCode.KEY_E` (same for the other options)
2) `onMount` accepts `(editor, monaco)` not `(monaco, editor)`
3) use version `v3.x.x` which does not have `onMount` property; switch to `v4.x.x`


here is the [fixed](https://codesandbox.io/s/monaco-editor-react---playground-forked-fxsxe?file=/src/index.js) version

**Comment by AndrewRayCode** [comment]
I have `"@monaco-editor/react": "^4.3.1",` in my package.json`

Was there a bad monaco publish, or a bad monaco-react publish?

<img width="1148" alt="Screen Shot 2022-02-04 at 10 47 55 AM" src="https://user-images.githubusercontent.com/79215/152585742-63ea7a7e-770f-429e-b4d3-e1651bf1c68c.png">

```
Property 'KEY_E' does not exist on type 'typeof KeyCode'. Did you mean 'KeyE'? ts(2551)
```

The official playground also shows `KeyE` etc https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance
