### ISSUE TITLE
Unregister (dispose?) language

### ISSUE THREAD

**Issue by gungorerhan** [suren-atoyan/monaco-react#343]
I would like to update or remove a custom language that I added. 
I looked around for a while, but could not find a solution.
Do you have any suggestions?

**Comment by suren-atoyan** [comment]
surprisingly, the language [register](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#register) doesn't return disposable. But [registerCompletionItemProvider](https://microsoft.github.io/monaco-editor/api/modules/monaco.languages.html#registerCompletionItemProvider) does. Hope this will help, otherwise, please refer this issue to the original [monaco-editor](https://github.com/microsoft/monaco-editor) package; not the React wrapper
