### ISSUE TITLE
Multiple editors on page cause duplicate definition of module warning

### ISSUE THREAD

**Issue by corydeppen** [suren-atoyan/monaco-react#360]
**Describe the bug**

Including multiple editor components on a page cause the warning `Duplicate definition of module '===anonymous1==='` to be displayed in the browser console.

**To Reproduce**

https://stackblitz.com/edit/vitejs-vite-viut12?file=src/App.tsx

**Expected behavior**

Warning should not be displayed in the browser console.

**Comment by i07** [comment]
@corydeppen This is because for each Editor it injects the script tag, at this moment is it's default behaviour coming from `monaco-loader` `https://github.com/suren-atoyan/monaco-loader`, so not from `monaco-react` or `monaco-editor`.

Where to begin to solve this, lies either with `monaco-loader` or with `monaco-react` (how the loader is implemented), there is a way with `monaco-loader` to not use script tags, and go on the node_modules version of `monaco-editor`, but that might not be compatible with `monaco-react` (I'm just not sure)

Anyhow, one way around it,  ***this is not recommended, but might help you during development*** and change the `node_modules/@monaco-editor/loader/lib/es/loader/index.js` (in my case I was using the `es` version, depending on your usage you might need to change the `cjs` or `umd` version of the file) file `injectScripts` function to check if the script tag already exists, and only return the tag if it doesn't. In this way you only end up with one single script tag. and you'll lose the console warning, I haven't tested that extensively, but that worked without issues for my use-case. Keep in mind that this will not work when you update your dependencies as the function will revert back to it's old state.

This is not a solution, but just giving you an indication where the problem starts.

Hope this helps a bit on your quest to solve this for you! Good luck

**Comment by suren-atoyan** [comment]
@corydeppen @i07 it's fixed on the latest version: `v4.4.4`
