### ISSUE TITLE
Doesn't the loader support relative paths?

### ISSUE THREAD

**Issue by lin-mt** [suren-atoyan/monaco-react#406]
**Is your feature request related to a problem? Please describe.**
<img width="929" alt="image" src="https://user-images.githubusercontent.com/58337359/191313825-0db49e88-a349-44f2-8906-11288adc1804.png">

**Describe the solution you'd like**
Loader can successfully load resources.

**Describe alternatives you've considered**

**Additional context**

**Comment by suren-atoyan** [comment]
@lin-mt no, you can't use relative paths in the loader config. Because it configures AMD loader - it will load resources from "outside". Check [this](https://github.com/suren-atoyan/monaco-react/issues/168#issuecomment-762336713) comment - it might help you; you just need to put the `editor` folder under the `/public`. Also, you can import it as a npm module, check [this](https://github.com/suren-atoyan/monaco-react#use-monaco-editor-as-an-npm-package)
