### ISSUE TITLE
Couldn't change l18n when passing monaco package from node_modules in loader.config

### ISSUE THREAD

**Issue by VladislavYeremeyev** [suren-atoyan/monaco-react#488]
**Describe the bug**
Couldn't change l18n when passing monaco package from node_modules in loader.config. It seems when monaco option is passed, other options are ignored.

**To Reproduce**

Consider the following code
```
import * as monaco from 'monaco-editor';

loader.config({ monaco, 'vs/nls': { availableLanguages: { '*': 'ru' } } });
```

**Expected behavior**
That code allows to import monaco-editor package from node_modules (instead of default CDN) and also to configure localization

**Screenshots**
If applicable, add screenshots to help to explain your problem.

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser Chrome
 - 113.0.5672.92 (Official Build) (arm64)

**Comment by suren-atoyan** [comment]
@VladislavYeremeyev 

when you pass `monaco` to `loader.config` other fields in `loader.config` are ignored, because they are `amd` configs and by passing `monaco` you start using `esm` version. So, you need to look for "How to localize in esm?", there is an open issue - [this](https://github.com/microsoft/monaco-editor/issues/1514) might be helpful.

**Comment by VladislavYeremeyev** [comment]
Thank you!
