### ISSUE TITLE
ControlledEditor doesn't fire onChange upon Undo/Redo

### ISSUE THREAD

**Issue by rosslovas** [suren-atoyan/monaco-react#51]
Undo and redo typically change the contents of a `ControlledEditor` but `onChange` doesn't fire. I see the code has an explicit check that prevents this which was added in 2.3.0, but it's not clear why. Undo and redo can change the content of the editor just like any other operation, so `onChange` should fire.

**Comment by travisdahl** [comment]
Just ran into the same issue. Interesting that its being intentionally prevented

**Comment by suren-atoyan** [comment]
Hello @rosslovas, @travisdahl. Sorry for the late answer guys.

I can approve - there is such kind of problem. We have faced it a couple of months ago. The explicit check you have already noticed is added intentionally. I'll work on it, and keep you up to date here.

Thank you for your support!

**Comment by jpeterson** [comment]
I'm interested in this as well 🙂 Can you recommend a workaround for now?

**Comment by suren-atoyan** [comment]
Hello @jpeterson, if you want to solve the problem in your particular case, I can suggest you use a custom controlled component made by you. I mean, the `Controlled Editor` component we have now is just a small wrapper around the main `Editor component`. So, you can easily implement it, for a hint you can examine [this file](https://github.com/suren-atoyan/monaco-react/blob/master/src/ControlledEditor/ControlledEditor.js). Until we will find a universal solution to solve problems of all.

**Comment by SivaKranthiKumar** [comment]
> 
> 
> Hello @rosslovas, @travisdahl. Sorry for the late answer guys.
> 
> I can approve - there is such kind of problem. We have faced it a couple of months ago. The explicit check you have already noticed is **added intentionally**. I'll work on it, and keep you up to date here.

Eager to know what problem made you to exclude undo & redo from onChange

**Comment by jdroigk** [comment]
SO I was experiencing the same issue, so I wrapped the controlled editor in a div then added a keyboard event. example

`
       <div tabIndex={-1} onKeyDown={_.debounce(event => this.hackCtrlZ(event), 250)}
        >
          <ControlledEditor
            language="json"
            theme={this.theme}
            value={this.value}
            options={options}
            onChange={_.debounce(this.onEditorChange, 250)}
            editorDidMount={this.onEditorDidMount}
          />
        </div>`

**Comment by RickeyWard** [comment]
I can't think of a reason why you wouldn't want the onChange event handler to fire with undo, and since the event is passed to the onChange handler you could easily do the check for isUndoing/isRedoing inside the actual onChange handler, but you can't go the other way.

For my case I just duplicated the controlledEditor and removed the check, but its otherwise identical and that is a little messy. Thanks

**Comment by SivaKranthiKumar** [comment]
> @SivaKranthiKumar I was experiencing the same issue, so I wrapped the controlled editor in a div then added a keyboard event. example
> 
> ` <div tabIndex={-1} onKeyDown={_.debounce(event => this.hackCtrlZ(event), 250)} > <ControlledEditor language="json" theme={this.theme} value={this.value} options={options} onChange={_.debounce(this.onEditorChange, 250)} editorDidMount={this.onEditorDidMount} /> </div>`

```javascript
editorDidMount = (getValue, editor) => {
    editor.focus();
    editor.onDidChangeModelContent((ev) => {
      const newValue = editor.getValue();
      console.log("editorDidMount -> newValue");
      this.props.updatePane(this.props.paneKey, newValue);
    });
  };
```

I used above code to fire the event for undo & redo using MonacoEditor component instead of ControlledEditor

**Comment by RickeyWard** [comment]
I think a cleaner solution is to have the ControlledEditor not eat those events (you could provide a prop for it but I don't think that's necessary and I'll show why. Here is how I solved it but I really think it should be in the component vanilla and her is my proposal as of why.

I created a `CustomControlledEditor` that removes the explicit check.

```JSX
import React, { useRef } from 'react';
import PropTypes from 'prop-types';

import Editor from '@monaco-editor/react';

const noop = _ => {};

const ControlledEditor = ({ value, onChange, editorDidMount, ...props }) => {
  const previousValue = useRef(value);

  const handleEditorDidMount = (getValue, editor) => {
    editor.onDidChangeModelContent(ev => {
      const currentValue = editor.getValue();
      if ((currentValue !== previousValue.current)) {
        previousValue.current = currentValue;
        const value = onChange(ev, currentValue);

        if (typeof value === 'string') {
          if (currentValue !== value) {
            editor.setValue(value);
          }
        }
      }
    });

    editorDidMount(getValue, editor);
  };

  return <Editor
    value={value}
    editorDidMount={handleEditorDidMount}
    _isControlledMode={true}
    {...props}
  />
};

ControlledEditor.propTypes = {
  value: PropTypes.string,
  editorDidMount: PropTypes.func,
  onChange: PropTypes.func,
};

ControlledEditor.defaultProps = {
  editorDidMount: noop,
  onChange: noop,
};

export default ControlledEditor;
```

now when using the editor, since you have access to the same event you can choose if you want to ignore undo-redo very easily in the onChange event handler. This is more versatile.

```JSX
<CustomControlledEditor
    language="javascript"
    value={myValue}
    onChange={(ev, value)=>{
    if(!(ev.isUndoing || ev.isRedoing)){
        //special undo redo behavior such as nothing
    } else {
        //not undo redo handling
    }
    // handling for both 
    }}
/>
```
The original dev has the issue of not wanting the event to fire, while many library consumers would expect it to. I think the arguments to the event handler are sufficient to decide behavior and the controllededitor wrapper shouldn't eat the events.

The work around is to just roll your own UncontrolledComponent, but I completely understand the reservations of doing that.

**Comment by suren-atoyan** [comment]
Hello @RickeyWard. I am the original dev of the wrapper and I can ensure you that there isn't any issue concerning to `"not wanting the event to fire"`.

So, the problem is that we have not found a way to make monaco editor "truly" controlled (as react dev understands it). That's why the main component exported from this library is not the controlled version of the component. The ControlledEditor we have now is the compromised version and we suggest using the uncontrolled version to avoid interfering in the nature of monaco. When we remove the check of undo/redo, the problem of the stack of changes arouses; you can use the version without undo/redo check, and try to do Command(Cntrl)+z after typing some code.

**Comment by RickeyWard** [comment]
I am using it, I've not seen any issue yet.

Monaco cant be truly controlled, but it could be more directly controlled. It would be to use it in advanced mode, so not using the editor's built in model (that is garbage collected when the editor instance changes). but instead create your own model on mount of component with `.createModel` and have the prop changes call the model permutation directly.

Most users probably don't actually need the editor 'controlled', but instead need the experience of it such as an onChange handler and a value that is always is sync with editor. React's declarative nature makes calling a function to get a value awkward.

**Comment by suren-atoyan** [comment]
@RickeyWard I am sorry, but I don't understand the part with `.createModel`; if it's possible, please exemplify it by code snippet. Thank you!

**Comment by RickeyWard** [comment]
The typical way of using monaco causes the editor to internally create a model aka `ITextModel` (what it calls a file editing context or representation of a file). This auto generated model's lifespan is controlled by the editor and behaves differently than if you manually created one with `editor.createModel(...)` followed by `editor.setModel`  found in the api here: https://microsoft.github.io/monaco-editor/api/modules/monaco.editor.html#createmodel. the `editor.onDidChangeModelContent` is just a bubbling of the `iTextModel.onDidChangeContent`. With the original reference to the created model you can directly bind to the events and call functions of the model that the editor is using, allowing you to do things such as reuse the same editor with many models or have a tighter bind for the controlled component experience, or even not render the editor during some situation and not lose your undo stack and scroll offset.

**Comment by travisdahl** [comment]
@RickeyWard I am using your implementation above and it works for `isUndoing` but i can still never get it to go into `isRedoing` block alone.  It seems like its still completely eating that event

```
if(isUndoing){
console.log('this works')
}

if(isRedoing){
console.log('this doesnt work')
}
```

**Comment by seraph0x** [comment]
@RickeyWard Thanks for sharing your implementation! This worked great for me to fix this bug.

I noticed another bug whereby holding backspace would skip some characters. (Basically, two onChange events would go up the React component chain before the first one's new value came back down the chain. I'm using Redux, so this might be related to a delay in Redux.)

I solved it by treating <Editor> as a true uncontrolled component (value prop is constant and all value updates happen imperatively) and debouncing the onChange handler which also drastically improved performance for the controlled editor. If anyone is interested, I'll include my modifications to @RickeyWard's code below.

<details><summary>ControlledEditor.jsx</summary>
<p>

``` jsx
import React, { useRef, useEffect, useMemo } from 'react'
import PropTypes from 'prop-types'
import debounce from 'lodash.debounce'

import Editor from '@monaco-editor/react'

const noop = (_) => {}

const DEFAULT_UPDATE_DEBOUNCE_DELAY = 100

const ControlledEditor = ({ value, onChange, editorDidMount, ...props }) => {
  const previousValue = useRef(value)
  const editorRef = useRef()
  const debouncedOnChange = useMemo(
    () =>
      debounce((event, value) => {
        previousValue.current = value
        onChange(event, value)
      }, DEFAULT_UPDATE_DEBOUNCE_DELAY),
    [onChange]
  )

  useEffect(() => {
    if (value !== previousValue.current && editorRef.current) {
      editorRef.current.setValue(value)
    }
    previousValue.current = value
  }, [value])

  const handleEditorDidMount = (getValue, editor) => {
    editorRef.current = editor
    editor.setValue(previousValue.current)
    editor.onDidChangeModelContent((ev) => {
      const currentValue = editor.getValue()
      if (currentValue !== previousValue.current) {
        debouncedOnChange(ev, currentValue)
      }
    })

    editorDidMount(getValue, editor)
  }

  return <Editor value="" editorDidMount={handleEditorDidMount} {...props} />
}

ControlledEditor.propTypes = {
  value: PropTypes.string,
  editorDidMount: PropTypes.func,
  onChange: PropTypes.func
}

ControlledEditor.defaultProps = {
  editorDidMount: noop,
  onChange: noop
}

export default ControlledEditor
```

</p>
</details>

I noticed that the `_isControlledEditor` prop can be removed with no apparent ill effects. All it seems to do is force tokenization on every update - why do you need that?

**Comment by patrickshipe** [comment]
Maybe I am missing something @suren-atoyan, but it seems that part of the issue is that the controlled editor will always run the `executeEdits` when `value` prop changes, even if `value === editorRef.current.getModel().getValue()`, which quickly clutters the undo stack. If the `value` prop changes but it strictly equals the model's current value, why do we make the update?

**Comment by suren-atoyan** [comment]
Hello @patrickshipe. You are right. There is no need, moreover, it will "spoil" the undo stack. I think the problem is that when I was rewriting it from a class component into a function component with hooks (a while ago), and converting big `componentDidMount` into small `useUpdate`s, I missed that check and got an illusion of necessity of `executeEdits` as there was a dependency array with `value` (something like this `useUpdate(...., [value])`). Long story short, that's a great catch, thank you, I am sure it will solve the problem with undo/redo. Let me check it today. And if everything is okay, I'll publish a new version.

**Comment by suren-atoyan** [comment]
@patrickshipe @seraph0x @RickeyWard @SivaKranthiKumar @jdroigk @jpeterson @travisdahl @rosslovas hello everyone 🙂 

The problem is solved.
A check has been missed during rewriting. Let's thank @patrickshipe for a great catch.

The new version (v3.4.2) has already published 🎉 
If it's possible, please check it.

Thank you all for your support!

**Comment by patrickshipe** [comment]
Awesome 🎉 🎉  happy to help :)

**Comment by obadakhalili** [comment]
It's still happening in version 4.2.1

**Comment by suren-atoyan** [comment]
> It's still happening in version 4.2.1

I couldn't reproduce it; could you please share a code snippet. Also check [this](https://codesandbox.io/s/confident-cloud-jmjl2?file=/src/App.js) - it works here

**Comment by obadakhalili** [comment]
> > It's still happening in version 4.2.1
> 
> I couldn't reproduce it; could you please share a code snippet. Also check [this](https://codesandbox.io/s/confident-cloud-jmjl2?file=/src/App.js) - it works here

Thanks for replying so fast. It's not. Try updating the value, and change it back to the original value. The first change will trigger the event handler, but the second one won't.

There's this work around:
```js
editor.onDidChangeModelContent(() => {
  console.log("onDidChangeModelContent -> newValue");
});
```
[But here's why it won't work for me](https://github.com/suren-atoyan/monaco-react/issues/241#issuecomment-876909575).
