### ISSUE TITLE
Support Offline

### ISSUE THREAD

**Issue by iddan** [suren-atoyan/monaco-react#54]
Hello,
We are using this package in [Cayley UI](https://github.com/cayleygraph/web) which is served locally and should work offline. But, I can see the code tries to access online URLs. Can you support offline use?

**Comment by suren-atoyan** [comment]
Hello @iddan. The code tries to access online URLs because by default this library uses CND as a source-target (check the default [config file](https://github.com/suren-atoyan/monaco-react/blob/master/src/config/index.js)). But of course, you can change this behavior and load monaco wherever you want ([check it](https://github.com/suren-atoyan/monaco-react#config)). Also, you can check this [discussion](https://github.com/suren-atoyan/monaco-react/issues/12).

**Comment by iddan** [comment]
I see. Thank you!
