### ISSUE TITLE
Jsx and typescirpt example?

### ISSUE THREAD

**Issue by remorses** [suren-atoyan/monaco-react#56]
How to set the `tsx` in the editor model extension when creating the editor?

**Comment by suren-atoyan** [comment]
Hello, @remorses.

If the question is about the ways to enable `tsx` with monaco editor, you can read about it [here](https://github.com/Microsoft/monaco-editor/issues/264). This particular library is just wrapper over the monaco editor. So, the question should be referred to link I mentioned.

If the question is about accessing monaco instance (to be able to do such things -> `monaco.languages...`), you can read about it [here](https://github.com/suren-atoyan/monaco-react#monaco-instance).

Let me know if it helps. Thank you!

**Comment by remorses** [comment]
I managed to set the `tsx` extension via editor.setModel
```tsx
         <Editor
            height='200px'
            language={language}
            editorDidMount={(_, editor) => {
                monaco.init().then((monaco) => {
                    const model = monaco.editor.createModel(
                        value,
                        language,
                        monaco.Uri.parse('file://index.tsx'),
                    )
                    editor.setModel(null)
                    editor.setModel(model)
                    monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
                        // ...
                    })
                })
            }}
        />
```

**Comment by arcanis** [comment]
@suren-atoyan It feels slightly wrong to use an async method in `editorDidMount` (there's a slight chance something could get out of sync depending on the React scheduling). Wouldn't it make sense to simply pass `monacoRef.current` as third parameter of the callback, since you already access it anyway to call `create`?

**Comment by suren-atoyan** [comment]
Hello @arcanis. Thank you for the feedback.

About exposing the `monaco instance` through `editorDidMount` please read [this discussion](https://github.com/suren-atoyan/monaco-react/issues/9).

About using async method in `editorDidMount`: if your assumption is based on the example above, I can say, that I have no idea about that code 🙂 It doesn't look ideal; I mean to say getting the instance of the monaco is possible from outside of the component, and If you want to somehow use it in the component, so, as it's an effect, for that purpose there is a `useEffect` 🙂 

Please read the discussion I've shared, and let me know your thoughts.

Thank you 🙂

**Comment by arcanis** [comment]
I needed to create a model in order to set a file name to the value inside the editor (important so that Intellisense works fine). I first started with the pattern described above, but since then I refined it into a cleaner pattern - so I don't actually have a personal use case anymore for getting the monaco instance in `componentDidMount`! 😛

I'm now doing the following:

```ts
export const MyEditor = React.lazy(async () => {
  const monaco = await monacoLoader.init();

  return ({value, onChange}: {value: string, onChange: (value: string) => void}) => {
    const model = useRef<monacoEditor.editor.ITextModel | null>(null);
    if (model.current === null)
      model.current = monaco.editor.createModel(value, `typescript`, monaco.Uri.file(`user-${Math.random()}.js`));

    useEffect(() => {
      return () => {
        model.current?.dispose();
      };
    }, []);

    const editorDidMount = useCallback((_, editor: monacoEditor.editor.IStandaloneCodeEditor) => {
      editor.setModel(model.current);
    }, []);

    return (
      <ControlledEditor editorDidMount={editorDidMount} language={`typescript`} value={value} onChange={(e, value) => onChange(value)}/>
    );
  };
});
```

> The monaco instance is something general and can affect all editor instances. So it would be better to export it separately.

Fwiw I'm not sure the two things are that connected. For example, if you take the closest similar API from React - events -, you'll see that you still can access the document instance (through `event.target.documentElement`) even if it's a general value. In the case of Monaco the editor instance doesn't contain the reference to the global Monaco, but that doesn't mean you're forbidden from exposing it.

All that being said, I don't have the use case anymore, so feel free to do as you please with #90!

**Comment by suren-atoyan** [comment]
The main idea was to keep things as clear as possible.

And as we haven't use case for that (😄), so, let me close it for now.

Anyway, thank you for your support!
