### ISSUE TITLE
TypeError: cancelable.cancel is not a function

### ISSUE THREAD

**Issue by patrick-sharp** [suren-atoyan/monaco-react#57]
**Describe the bug**
I randomly get this error crashing my application.

**To Reproduce**

I don't know how to reproduce this because it sometimes happens and sometimes does not.
It happens immediately when the route in which I load the monaco editor is navigated to.

**Expected behavior**
I expected it not to crash.
Setting breakpoints to pause on exception does not pause anywhere.
Perhaps by setting break points at all (before monaco loads) I allow it to wait and mount, causing `cancellable.cancel` to be a defined function.

**Screenshots**
![screencapture-localhost-3000-candidate-assessment-locald28cf7ce96cc4697aeb37d2b72612120-1582857075271](https://user-images.githubusercontent.com/26419596/75505175-62bd7400-598f-11ea-94f1-258f2eb6cffd.png)

**Desktop (please complete the following information):**
 - OS: Both Windows 10 and MacOs 10.15
 - Browser: Chrome
 - Version: 80

**Comment by suren-atoyan** [comment]
Hello @patrick-sharp 

hmmm, you know, it's a quite strange case. The `.cancel` method should be called only in those cases when we unmount the editor component but at the same time, we haven't completed the initialization process of the native monaco. But whatever, in any case, `cancelable.cancel` must exist (you can check it [here](https://github.com/suren-atoyan/monaco-react/blob/master/src/utils/makeCancelable.js#L13)).

Could you please make a reproducible example (maybe a code snippet), so that I'll be able to check your particular case, because I've just checked it one more time, and it seems to work without a hitch.

Thank you!

**Comment by travisdahl** [comment]
Using the latest version, Im using the `ControlledEditor` and I always get this warning, may be related...

`An error occurred during initialization of Monaco: operation is manually canceled`. 

I don't think theres anything crazy in my code...

```
      <ControlledEditor
        theme='dark'
        value={dslStr}
        onChange={onChange}
      />
```

**Comment by suren-atoyan** [comment]
Hello @travisdahl.

No, it just should be identified from the final catch and represented as an info, not an error.

The idea is, when you mount editor component it starts the initialization process of monaco behind the scenes, which is a quite complex process. There was such kind of "non-ideal" case: you mount editor component, it starts the initialization process of monaco, and you immediately unmount editor component; we, just, made cancelable the promise of initialization process, to be able to cancel it whenever we want. You see those messages, because, I assume, your app is doing some re-renders during startup, just it (which leads some instantaneous re-renders of the editor).

(BTW; in further re-renders, you don't see those messages, because the promise has already fulfilled, and there is nothing to cancel).

In next version, we just need to show it in a more proper way (not console.error, let's say, console.info and not with the prefix "An error occurred during...").

**Comment by suren-atoyan** [comment]
Hi @travisdahl. I've just published the new version - v3.4.1 🎉 The behavior of that message is fixed. 🙂

**Comment by suren-atoyan** [comment]
@sidwebworks which version do you use?

**Comment by sidwebworks** [comment]
Latest one, v4.4.5

**Comment by sidwebworks** [comment]
One thing I noticed is the error seems to originate either from the loader or useMonack hook, as the number of error logs are equal to how many components use the hook.

**Comment by sidwebworks** [comment]
Here is the live app https://web-pen.vercel.app @suren-atoyan

**Comment by sidwebworks** [comment]
@suren-atoyan Not yet but I plan to do it soon, and I have sent u an invitation to the repository :)

**Comment by sidwebworks** [comment]
@suren-atoyan It's opensource now https://github.com/sidwebworks/web-pen

**Comment by airhorns** [comment]
Did anyone find away around this in react strict mode?
