### ISSUE TITLE
Example code for DiffEditor?

### ISSUE THREAD

**Issue by nitslucky** [suren-atoyan/monaco-react#59]
**Is your feature request related to a problem? Please describe.**
Not able to find the example code for the DiffEditor. Just like [simple usage](https://github.com/suren-atoyan/monaco-react#simple-usage)[...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
`import DiffEditor from '@monaco-editor/react';`
`<DiffEditor original="rest" modified="rewe" height="90vh" language="json" />`

doing this process doesn't show up the DiffEditor.

**Comment by suren-atoyan** [comment]
Hello @nitslucky,

I see; the example provided by you won't work, because import is wrong `import DiffEditor from '@monaco-editor/react';`, it should be `import { DiffEditor } from '@monaco-editor/react';`.

Check it [here](https://codesandbox.io/s/monaco-editorreact---simple-usagediff-oggo3?fontsize=14&hidenavigation=1&theme=dark).

**Comment by suren-atoyan** [comment]
Hello @nitslucky, please let me know if it works, that we can close the issue.

**Comment by nitslucky** [comment]
> Hello @nitslucky, please let me know if it works, that we can close the issue.

yes, it did work. you can close this issue.

Thanks
