### ISSUE TITLE
Monaco support Content Security Policy (CSP)

### ISSUE THREAD

**Issue by hckhanh** [suren-atoyan/monaco-react#83]
**Is your feature request related to a problem? Please describe.**
I get the problem when I try to integrate monaco-react with CSP
Monaco always loads an inline script on html file

```js
      require.config({"paths":{"vs":"https://cdn.jsdelivr.net/npm/monaco-editor@0.20.0/min/vs"}});
      require(['vs/editor/editor.main'], function() {
        document.dispatchEvent(new Event('monaco_init'));
      });
```

**Describe the solution you'd like**
It should have a feature which allow to use file script instead of inline script

For now, I have to workaround by using: `'sha256-VK+pKL3MRvBY2BmWZQQrf4dm90dj3F2xZ7/V3Zs07ko='`

But when the version of monaco changes, I have to update the sha hash too.

**Comment by suren-atoyan** [comment]
Hello @hckhanh and thank you for opening this interesting issue.

So, first, let's take a look at the utility file, which runs in runtime and injects that very script into the HTML.

[Here it is](https://github.com/suren-atoyan/monaco-react/blob/master/src/utils/monaco.js#L68).

Here I have no options to give an src of a script. Because my script can be only in node_modules (we can also use CDN or load it from outside, but we will not consider it), which can be not accessible depending on the configuration of the user web server.

So, what we can do? The library has an option to be configured, read more about it [here](https://github.com/suren-atoyan/monaco-react#config).

It looks something like this:

```js
monaco.config({ paths: { vs: '...' } });
```

Solution:

`monac.config` now takes a single argument (which is not required). I can add a second argument or a special field for the first one, to give an opportunity to a developer, pass the path of the script, which will be set instead of the inline one.

How it will work:

From your side, you will do something like this:

```js
monaco.config({}, '/static/monaco-config.js'); // or monaco.config({ src: '/static/monaco-config.js' });
```

Under the hood it will work like this:

```js
...
  // see monaco-react/src/utils/monaco.js, line 65
  // I'll refactore it, and will change the function and script name
  createMainScript() {
    const mainScript = this.createScript();

    if (this.configFileSrc) {
      mainScript.src = this.configFileSrc;
    } else {
      mainScript.innerHTML = `
      require.config(${JSON.stringify(this.__config)});
      require(['vs/editor/editor.main'], function() {
        document.dispatchEvent(new Event('monaco_init'));
      });
    `;
    }

    mainScript.onerror = this.reject;

    return mainScript;
  }
...
```

How do you like it?

**Comment by hckhanh** [comment]
Hi @suren-atoyan, it sounds great with this solution.

**Comment by suren-atoyan** [comment]
Hello @hckhanh.

The new version (v3.3.2) is published 🎉 
It will be mentioned in the documentation in the further versions. But now you can try it in the new version.

It's gonna be something like this:

```js
monaco.config({
  paths: {
    vs: '[path-to-monaco]/vs',
  },
  src: '[path-to-monaco-config-file]/configFile.js',
});
```

Please check it and let me know if it works.

Thank you for your support!

**Comment by jay-deshmukh** [comment]
Hi @suren-atoyan is there any way we can bundle `https://cdn.jsdelivr.net/npm/monaco-editor@0.20.0/min/vs` statically in `monaco-react` need it for offline application.
