### ISSUE TITLE
Improve Monaco Instance usage example

### ISSUE THREAD

**Issue by D-to-the-K** [suren-atoyan/monaco-react#84]
**Is your feature request related to a problem? Please describe.**
I've spent more time than I'd like to admit trying to use the Monaco Instance example to include an editor for a custom language in my project. It would've been easier if the example showed a working editor :)

**Describe the solution you'd like**
A more clearer Monaco Instance example, showing a loaded editor on the page.

**Describe alternatives you've considered**
Something like this:
https://codesandbox.io/s/monaco-editorreact---monaco-instance-ydpez

**Additional context**
It shows up like this after changing the index.js and index.html files:
![image](https://user-images.githubusercontent.com/13403610/84837214-f03fd500-b00d-11ea-97fe-98676e04cdbf.png)

**Comment by suren-atoyan** [comment]
Hello @D-to-the-K.

Thank you for your note. I really loved the idea of your example, but couldn't replace the current one with yours, because I thought that it may confuse people; they may think that they have to handle the editor implementation if they use the `monaco` utility. I have already faced such kind of misunderstanding. But... your example was too good to let it go. I inspired by it and created a new section in the documentation about how you can create your own editor. [Here](https://github.com/suren-atoyan/monaco-react#create-your-own-editor) it is. And the example is almost identical to yours. Please check it out.

And thank you for your support.

**Comment by D-to-the-K** [comment]
That's great! Thanks :)
