### ISSUE TITLE
Alternative to automaticLayout: true

### ISSUE THREAD

**Issue by bragle** [suren-atoyan/monaco-react#89]
I don't think automaticLayout should be turned on by default. It is far too easy to just leave it turned on without realizing what performance impact is has. In the documentation, it's even discouraged to turn it on in the first place it on due to this.
Internally, as far as I know, the editor will add a setInterval with a function that checks if the parent containers width has changed every 100 ms. Something like this:
```js
let lastWidth = 0;

setInterval(() => {

  const currentWidth = editorContainer.offsetWidth;

  if (currentWidth === lastWidth) return;

  lastWidth = currentWidth;

  editor.layout();

}, 100);
```
##### Note: I haven't actually tested the code above, so it might not work. It's just there to make my point clearer 😺

Personally, I'd like it to just be disabled by default so people can solve the resizing issue however they'd like, but there are some alternatives.

1. Add an event listener on window resize and run `editor.layout();` on the next animation frame with `requestAnimationFrame`. This is how I've solved it, and I believe that this is a good alternative to resizing the editor when the window is resized.

2. Keep the automaticLayout option enabled, but be explicit about it. Maybe add a warning to the readme, or something like that. I was not aware of this until I stumbled upon another issue where this was mentioned, so there might be other people that isn't aware of this as well.

I think that the best solution would be to make an example of how it can be done with window resize and `requestAnimationFrame` as mentioned in alternative 1, an example of how it can be done with automaticLayout, and a short description of how editor.layout() works, but that's my personal opinion 😸

**Comment by suren-atoyan** [comment]
Hello @bragle. Thank you for your investigation.

I've just checked, and you were right, it set up a timer with 100ms and did some updates. I don't think the listening of the window resize and doing some updates according to that is the best solution, at least it will not cover what `automaticLayout ` does. The problem is that we want to "listen" parent container changes not the window changes. I think it will not cover all cases.

So, I'll think about it. Currently, there are several problems with `automaticLayout` in monaco version `0.20.0`. (you can check [this](https://github.com/microsoft/monaco-editor/issues/2057) [this](https://github.com/microsoft/monaco-editor/issues/1954) [this](https://github.com/microsoft/monaco-editor/issues/1930) and [this](https://github.com/suren-atoyan/monaco-react/issues/82)) Maybe it would be better to wait until they solve the problem in the next version (which is coming soon I hope) and based on that make decisions. I can find many workarounds, but it would be great to have the right solution out of the box.

Anyway, let's keep this issue open. I'll keep you up to date if there will be any news about this topic.

Thank you for your support.

**Comment by sujinleeme** [comment]
Hello, I faced the same problem and solved in a very hacky way. 
The div height of Editor is responsive.
  
```tsx

  const editorRef = useRef(null);

  const handleEditorDidMount = (editor) => {
    editorRef.current = editor;
    
    window.addEventListener('resize', () => {

      editor.layout({
        width: 'auto',
        height: 'auto',
      });

      const { width, height } = editorEl.getBoundingClientRect();
      editor.layout({
        width,
        height,
      });
    });
  };
  
 render (
       <div className={style.jsonEditor}>
        <Editor
          //...
          options={{
            automaticLayout: true, // not working
            scrollBeyondLastLine: false,
          }}
          // remove height
          onChange={handleEditorChange}
        />
      </div>
 )
```

**Comment by Andrew-web-coder** [comment]
I faced an issue where editor started to grow vertically infinitely and I had to set fixed height for parent element to fix that. Seems that layout does not work great when parents have `flex-grow:1`

**Comment by bragle** [comment]
@Andrew-web-coder I have no idea what your layout looks like, but you have to put `overflow: hidden` on a parent element. If you are unsure which one, put it on all of the parent elements, and remove them till you find the one 😸

On a different note, I've gone with an entirely different setup for monaco, where I'm using the [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) (with polyfill) which gets the job done for me. Anyway, I'm gonna go ahead and close this since I no longer use this package. @suren-atoyan if you want to keep this open for your own sake, go ahead and reopen it 😺
