### ISSUE TITLE
Model Marker no hover message

### ISSUE THREAD

**Issue by MRzNone** [suren-atoyan/monaco-react#93]
**Describe the bug**
In setting model marker, the underlines shows up, but the message was not displayed when hovering over it.

**To Reproduce**
This is the not working version
https://codesandbox.io/s/not-working-editor-marker-0nvvq

**Expected behavior**
```
let model = monaco.editor.createModel(
    'SELECT *s FROM `HAHAHHH'
);

monaco.editor.create(document.getElementById("container"), {
	model
});

monaco.editor.setModelMarkers(model, "owner", [
    {
        startLineNumber: 0,
        startColumn: 0,
        endLineNumber: 0,
        endColumn: 10,
        message: 'message',
        severity: monaco.MarkerSeverity.Warning
    },
]);
```
on https://microsoft.github.io/monaco-editor/playground.html will work

P.S.  copy the code to the playground.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome

**Additional context**

**Comment by suren-atoyan** [comment]
Hello @MRzNone.

Two notes about your sandbox code, that you've provided.

1) in the line 19 - `monaco.init().then(monacoEditor` -> `monacoEditor` should be `monacoInstance`; it's not editor instance (just naming convention)

2) in the line 27 - you should use `monacoInstance.MarkerSeverity.Warning` instead of `MarkerSeverity.Warning`.

So, the fixed version is [here](https://codesandbox.io/s/issue-93-o4g92?file=/src/index.tsx)

Please check it and let me know if everything is okay.

**Comment by MRzNone** [comment]
Thank you for the quick response!!
